### ISSUE TITLE
[User feedback] link to find age group proportion

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#160]
## dhis2

Username: catherine.bachy

## Browser
- Name: Mozilla
- Version: 5.0 (Windows)
- Platform: Win64

## User report
URL: https://dev.hmisocba.msf.es/dhis/api/apps/Reactive-Vaccination/index.html#/campaign-configuration

the UN table is not really user friendly and really heavy to open.
You can find the number of people by age group but then you have to calculate the proportion.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1565775924214449057.png )

**Comment by adrianq** [comment]
Not relevant anymore
