### ISSUE TITLE
[User feedback] Population percentage

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#161]
## dhis2

Username: catherine.bachy

## Browser
- Name: Mozilla
- Version: 5.0 (Windows)
- Platform: Win64

## User report
URL: https://dev.hmisocba.msf.es/dhis/api/apps/Reactive-Vaccination/index.html#/campaign-configuration

you allowed to provide different proportion per site which can be useful for some settings like host population vs displaced population. But then if we use this option it is not clear which distribution will be used to calculate the "campaign population distribution" in the software

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1565776130905621220.png )

**Comment by adrianq** [comment]
Not relevant anymore
