### ISSUE TITLE
[User feedback] vaccines doses used

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#162]
## dhis2

Username: catherine.bachy

## Browser
- Name: Mozilla
- Version: 5.0 (Windows)
- Platform: Win64

## User report
URL: https://dev.hmisocba.msf.es/dhis/api/apps/Reactive-Vaccination/index.html#/data-entry/a3mkqscScpo

During the campaign we collect:
vials used
doses administrated that is equal to "vaccine doses administrated" in the software.
So "vaccines doses used" should be "number of vials used"

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1565776911997121443.png )

**Comment by adrianq** [comment]
already implemented
