### ISSUE TITLE
[User feedback] AEFI

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#163]
## dhis2

Username: catherine.bachy

## Browser
- Name: Mozilla
- Version: 5.0 (Windows)
- Platform: Win64

## User report
URL: https://dev.hmisocba.msf.es/dhis/api/apps/Reactive-Vaccination/index.html#/data-entry/a3mkqscScpo

For the AEFI during a campaign you will be able to report immediately only the severe reaction. For the minors, they will be seen later in the health facilities and you don't always have the feedback straight after or even never...

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1565777133564267772.png )

**Comment by adrianq** [comment]
Not relevant anymore
