### ISSUE TITLE
[User feedback] AEB (Accidental exposure to blood)

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#164]
## dhis2

Username: catherine.bachy

## Browser
- Name: Mozilla
- Version: 5.0 (Windows)
- Platform: Win64

## User report
URL: https://dev.hmisocba.msf.es/dhis/api/apps/Reactive-Vaccination/index.html#/data-entry/a3mkqscScpo

In our screen this variable doesn't appear but we can see it in the user guide you provide us.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1565777226387523696.png )

**Comment by adrianq** [comment]
Not relevant anymore
