### ISSUE TITLE
Implement non-fixed core group

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app-blessed#25]
For Japanese_Encephalitis and Yellow_Fever it looks like the core age groups are not fixed as the start age is different based on the vaccination type. (See https://docs.google.com/spreadsheets/d/1b4J4gXftogCoXqE_9AwKce5rm1VZeCUp4T6OVEskop0/edit#gid=1500894891) This might be tricky as we will have to revisit the metadata design to take care of this or play around with the grey fields.

**Comment by adrianq** [comment]
We have taken care of this with a bit more complex implementation of step 4. It should do the trick but let's wait for Miriam feedback

**Comment by acasrod** [comment]
This might depend on how Miriam want to analyze it. Maybe it can be modelled as a 6-11 core age group with dissagregation and avoid complexity. Let's wait for her feedback

**Comment by adrianq** [comment]
@acasrod In theory what we have implemented should be enough but we will see in a month time once she starts playing with the app
