### ISSUE TITLE
[User feedback] Minor changes on Campaign Configurator

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#32]
## dhis2

Username: abigail.holman

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8082/api/apps/vaccination-app/index.html#/campaign-configurator/new

Hello!
First - I like this feedback feature. Very cool...

On the feedback: the only revision I would propose is the explanation: just clarify that the user clicks and drags to create a screenshot which will be submitted with the feedback. 

Second - I´m confused by the organization unit level vs. organization unit group. Questions are:

1) What is an organization unit group? (the drop down lists has medical services)
2) Can you select more than one organization unit? how would a campaign work if it were implemented in several organization units? i.e. several facilities?

Other comments...
1) It would help to have some simple instructions at the top of the page: e.g. "Select the organization unit which will implement the campaign" - and then "Name your campaign and choose dates for which data entry will be enabled", and then "select the antigens which will be administered"
English-language... "configurator" is not actually a word. I´ve been trying to decide whether we can invent it as a word.... but I´ve been thinking on this since january or so, and it still sounds strange. I would suggest just calling this section "campaign configuration" - or "Configure a new campaign" --- it is boring, but clear. 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-155169560119156302.png )

**Comment by adrianq** [comment]
Thanks for your comments Abi! Find my answers below:
- Feedback tool: Understood
- Organisation Unit Level vs Organisation Unit Group:
   -  Organisation Unit Group: Both OU Level and OU Group are DHIS2 concepts. You can find a brief explanation here https://docs.dhis2.org/2.30/en/user/html/manage_organisation_unit.html The ones displayed in the dropdowns have been configured and created by MSF and you can find them http://dev2.eyeseetea.com:8082/dhis-web-maintenance/#/list/organisationUnitSection/organisationUnitGroup and http://dev2.eyeseetea.com:8082/dhis-web-maintenance/#/list/organisationUnitSection/organisationUnitLevel Btw, this component is widely used in DHIS2 and we have just customised it a little bit (you can, for instance, find the same component at the very end of this dataset creation form http://dev2.eyeseetea.com:8082/dhis-web-maintenance/#/edit/dataSetSection/dataSet/add)
   - Yes, you can select multiple OUs. For now, we have enabled only level 6 OU and this may be confusing for you. If you expand the tree up to level 6 you will see there are several checkboxes and you can choose more than one. I think it is good that the user can only select OU at level 6 (or maybe 5) but it doesn't make sense to select a OU at level 1,2 or 3 for example.
- Ok with having a brief explanation at the top of the page. We added a help button (question mark on the right of the step title) but it is probably better to display it from the beginning at the top.
- I didn't know 'Configurator' was not actually a word. We have been wrongly using it for months, sorry for this. We will change it for the next release. Thanks!

**Comment by adrianq** [comment]
To do:
- [ ] Clarify that the user clicks and drags to create a screenshot which will be submitted with the feedback.
- [x] Add brief explanation at the top of the page
- [x] Change 'Campaign Configurator' for 'Campaign Configuration'
