### ISSUE TITLE
[User feedback] Organization units and groups - refinement

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#33]
## dhis2

Username: abigail.holman

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8082/api/apps/vaccination-app/index.html#/campaign-configurator/new

I´ve read the info on org unit and org unit groups... but this step remains confusing to me because of the level/association with a health service. 

So I´ll start with the left side of the screen shot: the only case in which a mass vaccination campaign might be associated with a specific service, is with the vaccination service. You would never run a campaign within the other services (ext consult, nut, outbreak and malaria opd, SRH, etc.) so having these options is just confusing and they should be removed. Any feedback that Miriam has provided overrides my comments here, but I think that a vaccination campaign would be associated with a facility - and potentially with a Vaccination service (though I don´t necessarily see the added value of associating it with a vaccination service) 

In light of this, the search option on the left should either allow the user to check a box next to the facility name (AXE BAMINGUI, PDS BANGBALI, or HOPITAL NDELE in the screensheet) OR only show the vaccination service. 

The right hand side of the screen: again I´m confused... the first drop-down menu only says "health service" - I guess this is describing Org Unit Level 6? There is only one option here, so I´m not clear what is being selected.  

The next drop down menu (Org Unit Group) option only makes sense to me if the campaign is implemented through several different facilities on that list and we want to group them in order to analyze the campaign across those facilities... this is from the perspective of a field user. If looking at it from the perspective of a HQ user, I might be interested in grouping the campaigns by region (Cells) - or by antigen - possible I would want to put them in a "vaccination" group... but 90% of the options on the drop down list are again health services and these are not relevant at any stage to the configuration of a vaccination campaign. 

As mentioned elsewhere, it would be very valuable to have an explanation next to each field where the user has to do something of what they are selecting and why ( we would like the option of decentralising configuration to exist, i.e. minimizing the amount of guess work or need to reference a manual.)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1551801761419717350.png )

**Comment by adrianq** [comment]
Thanks for you feedback Abigail! My comments:

- Left side: I agree 100% with you. Probably it is better to hide the last OU level and just display the facility name (AXE BAMINGUI, PDS BANGBALI, or HOPITAL NDELE) as you suggested. Will create a card for this.

- Right side: 
   - OU Level drop-down: In the default component you can choose any OU level. However, in here, we are only displaying the last level as it is the only one that can potentially makes sense (it is the level that contains the vaccination services). When you click on them all OUs at level 6 (Health Service) are selected. I agree this can be confusing and it is not an actual use case so if it is fine with you we will just remove this drop-down.
   - OU group drop-down: Your explanation is correct. Now we need to decide what to do. My suggestion is: We keep the drop down with all the OU Groups. When the user selects an OU group, behind the scenes, we will just select the OU that are an actual Vaccination Service. The other OU will be ignored. What do u think?

- Help: We already have a help button (question mark) at the right of the step and we discussed in another issue we will have a title for each step with a brief explanation of what to do. We can potentially have another question mark at the right of the OU group drop-down if we finally keep it. I think this should be enough...

Anyway, let's revisit this issue on Monday...

**Comment by adrianq** [comment]
- [x] Hide/Remove dropdown to select OU Level
- [x] Hide/Remove dropdown to select OU Level

To be discussed:
- [ ] Display up to OU L5
- [ ] Display only OUs that have a 'Vaccination' child
- [ ] Only OUs L5 are selectable
