### ISSUE TITLE
[User feedback] Where can one enter ´description/code/short name?´

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#38]
## dhis2

Username: abigail.holman

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8082/api/apps/vaccination-app/index.html#/campaign-configuration

Just that... these might be useful fields, but didn´t see an opportunity to enter information for these fields.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-155411437391222888.png )

**Comment by adrianq** [comment]
You are right. Either we remove them from the details or we add them in step 2. I guess it is better to hide them in the details to not overwhelm the user with many fields
