### ISSUE TITLE
[User feedback] None of the links are working

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#40]
## dhis2

Username: abigail.holman

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8082/api/apps/vaccination-app/index.html#/campaign-configuration

With the exception of "go to dashboard" I can´t use any of the links on this list.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-155411978670858627.png )

**Comment by adrianq** [comment]
Yes, that is correct. None of them is working at the moment except 'Go to Dashboard'. For the next release only 'Go to Data Entry' will be implemented. The rest of them will have to wait for the following milestone in May.
