### ISSUE TITLE
[User feedback] What is the check box for?

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#41]
## dhis2

Username: abigail.holman

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8082/api/apps/vaccination-app/index.html#/campaign-configuration

There doesn´t appear to be an action linked to checking the box next to a campaign name... 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1554119822785311119.png )

**Comment by adrianq** [comment]
The idea is for the application to potentially support bulk actions such as delete or sharing. At the moment, it's not used at all
