### ISSUE TITLE
[User feedback] Would be nice to be able to navigate back to the application landing page from this screen

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#42]
## dhis2

Username: abigail.holman

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8082/api/apps/vaccination-app/index.html#/campaign-configuration

There is currently no way to return to the landing page... you have to exit to dashboards or data entry it seems... 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-155411990524593114.png )

**Comment by adrianq** [comment]
This is solved as part of the next release:
![image](https://user-images.githubusercontent.com/6850223/55326769-74954f00-5480-11e9-9d4f-b74622b9ca3f.png)
