### ISSUE TITLE
[User feedback] Fix DHIS2 header in the app

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#43]
## dhis2

Username: abigail.holman

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8082/api/apps/vaccination-app/index.html#/campaign-configuration

It closes as soon as I hit the feedback button so I can´t take a screenshot, but when you click on the matrix to go into another app (e.g. data entry), the pulldown menu appears blank... so at the moment, there is actually no way to navigate to data entry (because the link in the drop down next to each campaign also doesn´t work)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1554120057535150470.png )

**Comment by adrianq** [comment]
This is certainly a bug with the DHIS2 header in production environments. We will look at eye and try to find a fix for the next release
