### ISSUE TITLE
[User feedback] Landing page links do not work

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/vaccination-app-blessed#50]
## dhis2

Username: miguel.sanchez

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
- Platform: Win32

## User report
URL: http://dev.eyeseetea.com:8082/api/apps/Reactive-Vaccination/index.html#/

Data entry and dashboard links kick you out of the system and a window to enter credential appears again, however credentials do not work from that window

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1555581478917301896.png )

**Comment by adrianq** [comment]
Yes, this is a bug. Unfortunately, it only happens in a production environment and we didn't realise while developing it. We will take care of it ASAP
